---
vbox_version: 7.2 # Determining this should be automated as per extension pack
vbox_version_url: http://download.virtualbox.org/virtualbox/LATEST-STABLE.TXT
vbox_share_name: shared
vbox_share_dir: /home/{{ ansible_user }}/shared
