---
protonvpn_repository_version: 1.0.8
protonvpn_repository_download_url: https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_{{ protonvpn_repository_version }}_all.deb
