---
- name: Create temporary build directory
  become: true
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: fzf_tmp_dir
  changed_when: false

- name: Download fzf binary
  become: true
  ansible.builtin.get_url:
    url: "{{ fzf_download_url }}"
    dest: "{{ fzf_tmp_dir.path }}"
    checksum: "sha256:{{ fzf_checksum_url }}"
    owner: root
    group: root
    mode: "0755"
  changed_when: false

- name: Extract from archive
  become: true
  ansible.builtin.unarchive:
    src: "{{ fzf_tmp_dir.path }}/{{ fzf_filename }}"
    dest: "{{ fzf_tmp_dir.path }}"
    owner: root
    group: root
    remote_src: true

- name: Copy fzf file to bin
  become: true
  ansible.builtin.copy:
    src: "{{ fzf_tmp_dir.path }}/fzf"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0755"
    remote_src: true

- name: Ensure user profile directory exists
  become: true
  ansible.builtin.file:
    dest: /home/{{ ansible_user }}/.profile.d
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"

- name: Source fzf
  become: true
  ansible.builtin.copy:
    src: fzf.sh
    dest: /home/{{ ansible_user }}/.profile.d/fzf.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
