---
owasp_version: 2.16.1
owasp_install_parent_dir: /opt/owaspzap-versions
owasp_install_dir: "{{ owasp_install_parent_dir }}/owaspzap-{{ owasp_version }}"
owasp_filename: ZAP_{{ owasp_version }}_Linux.tar.gz
owasp_download_url: https://github.com/zaproxy/zaproxy/releases/download/v{{ owasp_version }}/{{ owasp_filename }}
owasp_bin: /usr/local/bin/owaspzap
